# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 146f51fc669107f0ad71f81b29f93803cb5a6c9da8a89016260874b3f8dc9210d91b02f7e59b5f287d55b65c76e6a13a4d75115cec0227a725a7c70b27517e7e

test:
  secret_key_base: dfaa45d2d82d6cf2e52899f6f5416efbe94d82082551bd46d74d4bce5c0acb99bba9aff37033d3bd55a5594e2dd0c0313cf3298286bad5b7e1a4bac61a9f01f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
